add additional image drawing methods and operators
microsoft/psi pull request #130
Opened 2021-05-01 08:20 UTC by tteichmeister

Hi, 

It would be helpful to provide additional drawing functions for the image. 
Especially to fill a rectangle or a circle. Currently it is only possible to draw a rectangle/circle but not to fill it. 

Furthermore, an additional function to draw a text with a background color would be good. 
Especially if you want to label objects and other stuff, with a background color as a contrast, it can help to improve the readability of the text.

(Here I marked the object with `DrawRectangle` and using the new `DrawText` method to draw the text below)
![image](https://user-images.githubusercontent.com/10572975/116775883-d791af80-aa65-11eb-9c20-af568aadfeb8.png)

Therefore I provided 3 methods: 
- `FillRectangle` 
- `FillCircle`
- `DrawText` (including an additional color for the background color)

I also including the operators which are also included for the existing `DrawText`, `DrawRectangle`...

2021-05-03 22:40 UTC, chitsaw requested changes
Thank you for submitting this PR - just a couple of tiny changes but otherwise everything looks great! Thanks also for including unit tests :-). For some reason there is one test (Image_GrayDrawTestWithBackground) that fails the CI build due to too many different pixels vs the reference image. I wonder if that test passes for you at all? We've sometimes noticed in the past that some of these imaging tests can fail on some machines but not others, possibly due to differences in GDI+ versions. There are `tolerance` and `outlier` parameters in the `AssertAreImagesEqual` method for that reason, but normally the default tolerances have worked for us.

2021-05-03 22:40 UTC, chitsaw commented on Sources/Imaging/Microsoft.Psi.Imaging/ImageExtensions.cs
> +        /// <param name="p0">Pixel coordinates for center of circle.</param>
upper-left corner of the text

2021-05-03 22:40 UTC, chitsaw commented on Sources/Imaging/Test.Psi.Imaging.Windows/ImageTester.cs
> +            sharedImage.Resource.ToBitmap().Save(@"C:\Users\tteichmeister\Desktop\fill_rect.bmp");
I think this was temporary and can be removed

2021-05-03 22:40 UTC, chitsaw commented on Sources/Imaging/Test.Psi.Imaging.Windows/ImageTester.cs
> +            sharedImage.Resource.ToBitmap().Save(@"C:\Users\tteichmeister\Desktop\fill_circle.bmp");
remove

2021-05-04 08:00 UTC, tteichmeister commented
> Thank you for submitting this PR - just a couple of tiny changes but otherwise everything looks great! Thanks also for including unit tests :-). For some reason there is one test (Image_GrayDrawTestWithBackground) that fails the CI build due to too many different pixels vs the reference image. I wonder if that test passes for you at all? We've sometimes noticed in the past that some of these imaging tests can fail on some machines but not others, possibly due to differences in GDI+ versions. There are `tolerance` and `outlier` parameters in the `AssertAreImagesEqual` method for that reason, but normally the default tolerances have worked for us.

@chitsaw 
It's strange, because before I submitted it, the Test was working on my machine. When I was doing it now again, this test didn't passed also on my machine. So I provided a new verification image for this test. I think I uploaded the wrong one. Since the checks passed now :-)

Thank you for your review and to let me contribute this to your project :-).

2021-05-04 15:58 UTC, chitsaw approved these changes

2021-05-04 16:00 UTC, merged

2021-05-04 16:00 UTC, chitsaw commented
@tteichmeister thanks for making those changes. Yes, the tests pass now with the new image. Thanks so much for your contributions!