Add QUICKSTART.md for LINUX
microsoft/psi pull request #88
Opened 2020-09-11 20:26 UTC by dcmartin

This is initial process to setup `\psi` on Ubuntu LINUX versions 18.04 and 20.04; working correctly on AMD64; still to be tested on aarch64/arm64 and armhf/armv7.

2020-09-15 23:11 UTC, chitsaw requested changes
Thanks for taking the time to write this up!

2020-09-15 23:11 UTC, chitsaw commented on QUICKSTART.md
> +Install `.Net Core` version 3.1; download from [here](https://dotnet.microsoft.com/download/dotnet-core/3.1); select the appropriate **OS**
Isn't this step pretty much covered under Step 2? If so it can be removed.

2020-09-22 17:11 UTC, dcmartin commented on QUICKSTART.md
> +wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
Clarified that instructions are for both 18.04 and 20.04

2020-09-22 17:15 UTC, dcmartin commented on QUICKSTART.md
> +
Added new top-level section for LINUX with option for future OS specifications.

2020-09-23 23:19 UTC, chitsaw approved these changes
Thanks for the changes!

2020-09-23 23:20 UTC, merged